/**
 * Additional Trivia questions (easy / medium / hard).
 * Evergreen facts only — no prices, rankings-of-the-moment, or promotions.
 */

function q(id, category, question, answers, correctIndex, difficulty) {
  return Object.freeze({
    id,
    category,
    question,
    answers: Object.freeze(answers.slice()),
    correctIndex,
    difficulty,
  });
}

const EXTRA_QUESTIONS = [
  // geography
  q("xgeo-01", "geography", "Which African lake is the world's second-largest freshwater lake by surface area?", ["Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Chad"], 0, "medium"),
  q("xgeo-02", "geography", "The Strait of Gibraltar separates Spain from which country?", ["Morocco", "Algeria", "Portugal", "Tunisia"], 0, "easy"),
  q("xgeo-03", "geography", "Which country is both a continent and an island nation?", ["Australia", "Greenland", "Madagascar", "Iceland"], 0, "easy"),
  q("xgeo-04", "geography", "What is the capital of New Zealand?", ["Wellington", "Auckland", "Christchurch", "Dunedin"], 0, "medium"),
  q("xgeo-05", "geography", "The Atacama Desert is primarily in which country?", ["Chile", "Peru", "Argentina", "Bolivia"], 0, "medium"),
  q("xgeo-06", "geography", "Which river flows through Baghdad?", ["Tigris", "Euphrates", "Jordan", "Nile"], 0, "hard"),
  q("xgeo-07", "geography", "Which European capital sits on the River Danube?", ["Budapest", "Prague", "Warsaw", "Stockholm"], 0, "medium"),
  q("xgeo-08", "geography", "Which mountain is the highest in Africa?", ["Kilimanjaro", "Mount Kenya", "Ras Dashen", "Toubkal"], 0, "easy"),
  q("xgeo-09", "geography", "The Magellan Strait is at the southern tip of which continent?", ["South America", "Africa", "Australia", "Antarctica"], 0, "medium"),
  q("xgeo-10", "geography", "What is the capital of Ethiopia?", ["Addis Ababa", "Asmara", "Khartoum", "Nairobi"], 0, "medium"),
  q("xgeo-11", "geography", "Which sea is connected to the Atlantic by the Bosporus and Dardanelles?", ["Black Sea", "Caspian Sea", "Red Sea", "Baltic Sea"], 0, "hard"),
  q("xgeo-12", "geography", "Which country has the most time zones, including overseas territories?", ["France", "Russia", "United States", "United Kingdom"], 0, "hard"),
  q("xgeo-13", "geography", "Lake Baikal is in which country?", ["Russia", "Mongolia", "China", "Kazakhstan"], 0, "medium"),
  q("xgeo-14", "geography", "Which desert covers much of Botswana?", ["Kalahari", "Namib", "Sahara", "Karoo"], 0, "hard"),
  q("xgeo-15", "geography", "Which European country is doubly landlocked?", ["Liechtenstein", "Switzerland", "Austria", "Luxembourg"], 0, "hard"),
  q("xgeo-16", "geography", "The island of Tasmania is part of which country?", ["Australia", "New Zealand", "Indonesia", "Papua New Guinea"], 0, "easy"),
  q("xgeo-17", "geography", "Which U.S. state has the longest shoreline, including islands?", ["Alaska", "Florida", "California", "Hawaii"], 0, "hard"),
  q("xgeo-18", "geography", "Which city is the capital of Colombia?", ["Bogotá", "Medellín", "Cali", "Cartagena"], 0, "medium"),
  q("xgeo-19", "geography", "The Gobi Desert lies mainly in Mongolia and which other country?", ["China", "Russia", "Kazakhstan", "India"], 0, "medium"),
  q("xgeo-20", "geography", "Which African country is completely surrounded by South Africa?", ["Lesotho", "Eswatini", "Botswana", "Namibia"], 0, "hard"),
  q("xgeo-21", "geography", "Which Canadian province is the only one that borders the Pacific Ocean?", ["British Columbia", "Alberta", "Yukon", "Manitoba"], 0, "hard"),
  q("xgeo-22", "geography", "The Mekong River empties into the sea in which country?", ["Vietnam", "Cambodia", "Laos", "Thailand"], 0, "hard"),
  q("xgeo-23", "geography", "Which island is the largest in the Mediterranean?", ["Sicily", "Sardinia", "Cyprus", "Crete"], 0, "medium"),
  q("xgeo-24", "geography", "Which country has the city of Kraków?", ["Poland", "Czechia", "Hungary", "Slovakia"], 0, "easy"),
  q("xgeo-25", "geography", "The Great Dividing Range is in which country?", ["Australia", "New Zealand", "Canada", "South Africa"], 0, "medium"),
  q("xgeo-26", "geography", "Which capital city is on the island of Zealand?", ["Copenhagen", "Stockholm", "Helsinki", "Reykjavík"], 0, "hard"),

  // history
  q("xhis-01", "history", "In which year did the Cuban Missile Crisis take place?", ["1962", "1959", "1968", "1956"], 0, "hard"),
  q("xhis-02", "history", "Who was the first emperor of a unified China?", ["Qin Shi Huang", "Confucius", "Kublai Khan", "Sun Yat-sen"], 0, "medium"),
  q("xhis-03", "history", "The Battle of Hastings took place in which year?", ["1066", "1215", "1415", "1588"], 0, "medium"),
  q("xhis-04", "history", "Which empire built Machu Picchu?", ["Inca", "Aztec", "Maya", "Olmec"], 0, "easy"),
  q("xhis-05", "history", "The Magna Carta was sealed in which century?", ["13th", "11th", "15th", "17th"], 0, "medium"),
  q("xhis-06", "history", "Who wrote the 95 Theses in 1517?", ["Martin Luther", "John Calvin", "Erasmus", "John Knox"], 0, "medium"),
  q("xhis-07", "history", "Which war ended with the Treaty of Versailles in 1919?", ["World War I", "World War II", "Franco-Prussian War", "Crimean War"], 0, "easy"),
  q("xhis-08", "history", "The Meiji Restoration began in which country?", ["Japan", "China", "Korea", "Thailand"], 0, "medium"),
  q("xhis-09", "history", "Which civilization used Linear B script?", ["Mycenaean", "Minoan only", "Phoenician", "Etruscan"], 0, "hard"),
  q("xhis-10", "history", "Who is generally identified as the last emperor of the Western Roman Empire?", ["Romulus Augustulus", "Julius Caesar", "Constantine", "Nero"], 0, "hard"),
  q("xhis-11", "history", "The Code of Hammurabi originated in which ancient region?", ["Babylonia", "Egypt", "Persia", "Assyria only"], 0, "medium"),
  q("xhis-12", "history", "Which explorer's expedition completed the first circumnavigation of Earth?", ["Magellan's (Elcano completed it)", "Columbus", "Cook", "da Gama"], 0, "hard"),
  q("xhis-13", "history", "The Haitian Revolution began in which decade?", ["1790s", "1810s", "1760s", "1830s"], 0, "hard"),
  q("xhis-14", "history", "The Rosetta Stone was found during a campaign of which general?", ["Napoleon", "Alexander the Great", "Julius Caesar", "Nelson"], 0, "medium"),
  q("xhis-15", "history", "Which dynasty built the majority of the existing Great Wall of China?", ["Ming", "Qin", "Han", "Tang"], 0, "hard"),
  q("xhis-16", "history", "The Battle of Stalingrad was fought during which war?", ["World War II", "World War I", "Russian Civil War", "Napoleonic Wars"], 0, "easy"),
  q("xhis-17", "history", "Who was the British monarch at the start of World War I?", ["George V", "Victoria", "Edward VII", "George VI"], 0, "hard"),
  q("xhis-18", "history", "The Ottoman Empire's capital after 1453 was:", ["Constantinople (Istanbul)", "Ankara", "Baghdad", "Cairo"], 0, "medium"),
  q("xhis-19", "history", "The printing press with movable type in Europe is credited to:", ["Johannes Gutenberg", "William Caxton", "Aldus Manutius", "Benjamin Franklin"], 0, "easy"),
  q("xhis-20", "history", "Which African kingdom was famous for the city of Timbuktu?", ["Mali", "Zulu", "Axum", "Kongo"], 0, "medium"),
  q("xhis-21", "history", "The Treaty of Tordesillas (1494) divided lands between Spain and:", ["Portugal", "England", "France", "the Netherlands"], 0, "hard"),
  q("xhis-22", "history", "The Bolsheviks seized power in Russia in:", ["1917", "1905", "1922", "1914"], 0, "medium"),
  q("xhis-23", "history", "Which civilization built Angkor Wat?", ["Khmer", "Thai", "Burmese", "Javanese Majapahit"], 0, "medium"),
  q("xhis-24", "history", "The Peloponnesian War was fought mainly between Athens and:", ["Sparta", "Persia", "Macedonia", "Carthage"], 0, "medium"),
  q("xhis-25", "history", "Who issued the Edict of Milan that tolerated Christianity in the Roman Empire?", ["Constantine", "Nero", "Augustus", "Justinian"], 0, "hard"),
  q("xhis-26", "history", "The first successful powered airplane flight by the Wright brothers was in:", ["1903", "1899", "1914", "1908"], 0, "easy"),

  // science
  q("xsci-01", "science", "What particle carries a negative electric charge in an atom?", ["Electron", "Proton", "Neutron", "Photon"], 0, "easy"),
  q("xsci-02", "science", "What is the chemical symbol for tungsten?", ["W", "Tu", "Tn", "Tg"], 0, "hard"),
  q("xsci-03", "science", "DNA's double helix was described in 1953 by Watson and:", ["Crick", "Franklin only as sole author", "Pauling", "Mendel"], 0, "medium"),
  q("xsci-04", "science", "Which planet has the Great Red Spot?", ["Jupiter", "Saturn", "Mars", "Neptune"], 0, "easy"),
  q("xsci-05", "science", "What is the SI unit of electric current?", ["Ampere", "Volt", "Ohm", "Watt"], 0, "medium"),
  q("xsci-06", "science", "Photosynthesis in plants primarily occurs in which organelle?", ["Chloroplast", "Mitochondrion", "Nucleus", "Ribosome"], 0, "easy"),
  q("xsci-07", "science", "What is the most abundant gas in Earth's atmosphere?", ["Nitrogen", "Oxygen", "Carbon dioxide", "Argon"], 0, "easy"),
  q("xsci-08", "science", "The speed of light in vacuum is approximately:", ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "3 × 10¹⁰ m/s", "300 m/s"], 0, "medium"),
  q("xsci-09", "science", "Which force holds protons and neutrons in an atomic nucleus?", ["Strong nuclear force", "Gravity", "Electromagnetism", "Weak force only"], 0, "hard"),
  q("xsci-10", "science", "A light-year measures:", ["Distance", "Time", "Brightness", "Mass"], 0, "easy"),
  q("xsci-11", "science", "Which blood type is typically the universal donor for red cells?", ["O negative", "AB positive", "A positive", "B negative"], 0, "medium"),
  q("xsci-12", "science", "Tectonic plates move on Earth's:", ["Asthenosphere", "Inner core", "Stratosphere", "Outer core only"], 0, "hard"),
  q("xsci-13", "science", "Which vitamin is produced in skin exposed to sunlight?", ["Vitamin D", "Vitamin C", "Vitamin B12", "Vitamin K"], 0, "easy"),
  q("xsci-14", "science", "What is the pH of a neutral aqueous solution at 25°C?", ["7", "0", "14", "1"], 0, "easy"),
  q("xsci-15", "science", "Which astronomer proposed a heliocentric model in De revolutionibus?", ["Copernicus", "Ptolemy", "Brahe", "Kepler"], 0, "medium"),
  q("xsci-16", "science", "Sound cannot travel through:", ["Vacuum", "Water", "Steel", "Air"], 0, "easy"),
  q("xsci-17", "science", "Which particle is a boson that gives mass via the Higgs field?", ["Higgs boson", "Electron", "Neutrino", "Proton"], 0, "hard"),
  q("xsci-18", "science", "The ozone layer is mainly in the:", ["Stratosphere", "Troposphere", "Mesosphere", "Thermosphere"], 0, "medium"),
  q("xsci-19", "science", "Which element has atomic number 6?", ["Carbon", "Oxygen", "Nitrogen", "Boron"], 0, "easy"),
  q("xsci-20", "science", "CRISPR-Cas9 is primarily used for:", ["Gene editing", "MRI imaging", "Nuclear fusion", "Weather prediction"], 0, "medium"),
  q("xsci-21", "science", "A black hole's event horizon is the boundary beyond which:", ["Light cannot escape", "Time stops for distant observers only as a metaphor", "Matter becomes plasma only", "Gravity becomes repulsive"], 0, "medium"),
  q("xsci-22", "science", "Which moon is the largest in the Solar System?", ["Ganymede", "Titan", "The Moon", "Callisto"], 0, "hard"),
  q("xsci-23", "science", "Platelets in blood are mainly involved in:", ["Clotting", "Oxygen transport", "Antibody production", "Digesting bacteria only"], 0, "medium"),
  q("xsci-24", "science", "The second law of thermodynamics says isolated systems tend to increase:", ["Entropy", "Energy", "Order always", "Temperature always"], 0, "hard"),
  q("xsci-25", "science", "Which gas do legumes often help fix from the air via bacteria?", ["Nitrogen", "Oxygen", "Helium", "Methane"], 0, "medium"),
  q("xsci-26", "science", "Io, Europa, Ganymede, and Callisto orbit which planet?", ["Jupiter", "Saturn", "Uranus", "Neptune"], 0, "medium"),

  // math
  q("xmat-01", "math", "What is the value of π rounded to two decimal places?", ["3.14", "3.41", "3.04", "2.14"], 0, "easy"),
  q("xmat-02", "math", "What is 2⁵?", ["32", "16", "64", "10"], 0, "easy"),
  q("xmat-03", "math", "How many degrees are in the interior angles of a triangle combined?", ["180", "90", "360", "270"], 0, "easy"),
  q("xmat-04", "math", "What is the square root of 144?", ["12", "14", "16", "18"], 0, "easy"),
  q("xmat-05", "math", "A prime number is divisible by:", ["Only 1 and itself", "Any even number", "10", "Every odd number"], 0, "easy"),
  q("xmat-06", "math", "What is 7! (7 factorial)?", ["5040", "720", "2520", "40320"], 0, "medium"),
  q("xmat-07", "math", "The derivative of x² with respect to x is:", ["2x", "x", "x²", "2"], 0, "medium"),
  q("xmat-08", "math", "What is the next prime after 31?", ["37", "33", "35", "39"], 0, "medium"),
  q("xmat-09", "math", "How many sides does a dodecagon have?", ["12", "10", "8", "20"], 0, "medium"),
  q("xmat-10", "math", "If a circle has radius 5, its area is:", ["25π", "10π", "5π", "50π"], 0, "medium"),
  q("xmat-11", "math", "What is log₁₀(1000)?", ["3", "2", "4", "100"], 0, "medium"),
  q("xmat-12", "math", "The sum of the interior angles of a pentagon is:", ["540°", "360°", "720°", "900°"], 0, "hard"),
  q("xmat-13", "math", "What is the hypotenuse of a right triangle with legs 3 and 4?", ["5", "6", "7", "12"], 0, "easy"),
  q("xmat-14", "math", "e, the base of natural logarithms, is approximately:", ["2.718", "3.142", "1.618", "1.414"], 0, "medium"),
  q("xmat-15", "math", "A set with n elements has how many subsets?", ["2ⁿ", "n²", "n!", "2n"], 0, "hard"),
  q("xmat-16", "math", "What is the median of 3, 9, 1, 7, 5?", ["5", "7", "9", "4"], 0, "medium"),
  q("xmat-17", "math", "sin(90°) equals:", ["1", "0", "0.5", "√2/2"], 0, "medium"),
  q("xmat-18", "math", "The golden ratio φ is the positive solution of:", ["x² = x + 1", "x² = 2", "x² = x − 1", "x³ = x + 1"], 0, "hard"),
  q("xmat-19", "math", "How many faces does a cube have?", ["6", "8", "12", "4"], 0, "easy"),
  q("xmat-20", "math", "The infinite series 1 + 1/2 + 1/4 + 1/8 + … sums to:", ["2", "1", "infinity", "1.5"], 0, "hard"),

  // entertainment
  q("xent-01", "entertainment", "Who composed The Four Seasons?", ["Vivaldi", "Bach", "Mozart", "Handel"], 0, "easy"),
  q("xent-02", "entertainment", "Which novel begins, \"Call me Ishmael\"?", ["Moby-Dick", "Treasure Island", "Heart of Darkness", "Robinson Crusoe"], 0, "medium"),
  q("xent-03", "entertainment", "Pac-Man was first released by which company?", ["Namco", "Nintendo", "Sega", "Atari"], 0, "medium"),
  q("xent-04", "entertainment", "The film Casablanca is set mainly in which city?", ["Casablanca", "Paris", "Lisbon", "Algiers"], 0, "easy"),
  q("xent-05", "entertainment", "Who wrote Pride and Prejudice?", ["Jane Austen", "Charlotte Brontë", "George Eliot", "Mary Shelley"], 0, "easy"),
  q("xent-06", "entertainment", "The Mona Lisa is displayed primarily in which museum?", ["Louvre", "Prado", "Uffizi", "Tate Modern"], 0, "easy"),
  q("xent-07", "entertainment", "Tetris was created by Alexey Pajitnov in which country?", ["Soviet Union (Russia)", "Japan", "United States", "Hungary"], 0, "medium"),
  q("xent-08", "entertainment", "How many keys does a standard modern piano have?", ["88", "76", "61", "49"], 0, "easy"),
  q("xent-09", "entertainment", "Who directed the 1977 film Star Wars: A New Hope?", ["George Lucas", "Steven Spielberg", "Ridley Scott", "James Cameron"], 0, "easy"),
  q("xent-10", "entertainment", "The Odyssey is traditionally attributed to:", ["Homer", "Virgil", "Sophocles", "Ovid"], 0, "easy"),
  q("xent-11", "entertainment", "Mario first appeared in which 1981 arcade game?", ["Donkey Kong", "Super Mario Bros.", "Mario Bros.", "Punch-Out!!"], 0, "medium"),
  q("xent-12", "entertainment", "Guernica is a painting by:", ["Picasso", "Dalí", "Miró", "Matisse"], 0, "medium"),
  q("xent-13", "entertainment", "Which Shakespeare play includes the characters Rosencrantz and Guildenstern?", ["Hamlet", "Macbeth", "Othello", "King Lear"], 0, "medium"),
  q("xent-14", "entertainment", "The video game The Legend of Zelda series is published by:", ["Nintendo", "Sony", "Sega", "Square Enix"], 0, "easy"),
  q("xent-15", "entertainment", "Which composer wrote the opera The Magic Flute?", ["Mozart", "Verdi", "Wagner", "Puccini"], 0, "medium"),
  q("xent-16", "entertainment", "Citizen Kane is often associated with which director-star?", ["Orson Welles", "Alfred Hitchcock", "Charlie Chaplin", "John Ford"], 0, "medium"),
  q("xent-17", "entertainment", "Who wrote One Hundred Years of Solitude?", ["Gabriel García Márquez", "Pablo Neruda", "Isabel Allende", "Jorge Luis Borges"], 0, "medium"),
  q("xent-18", "entertainment", "The Starry Night was painted by:", ["Vincent van Gogh", "Claude Monet", "Paul Cézanne", "Edvard Munch"], 0, "easy"),
  q("xent-19", "entertainment", "Final Fantasy is a long-running series primarily from:", ["Square (Square Enix)", "Capcom", "Konami", "Bandai Namco"], 0, "medium"),
  q("xent-20", "entertainment", "Which ballet features the music of Tchaikovsky's Dance of the Sugar Plum Fairy?", ["The Nutcracker", "Swan Lake", "Giselle", "Coppelia"], 0, "medium"),
  q("xent-21", "entertainment", "Who wrote The Divine Comedy?", ["Dante Alighieri", "Petrarch", "Boccaccio", "Chaucer"], 0, "medium"),
  q("xent-22", "entertainment", "The Game Boy launched in:", ["1989", "1985", "1993", "1981"], 0, "hard"),
  q("xent-23", "entertainment", "Which artist cut off part of his own ear?", ["Vincent van Gogh", "Paul Gauguin", "Toulouse-Lautrec", "Rembrandt"], 0, "easy"),
  q("xent-24", "entertainment", "The Lord of the Rings was written by:", ["J. R. R. Tolkien", "C. S. Lewis", "George R. R. Martin", "Terry Pratchett"], 0, "easy"),
  q("xent-25", "entertainment", "Metroid's original protagonist is known as:", ["Samus Aran", "Zelda", "Lara Croft", "Cortana"], 0, "medium"),
  q("xent-26", "entertainment", "Which symphony is nicknamed the Eroica?", ["Beethoven's 3rd", "Mozart's 40th", "Haydn's Surprise", "Schubert's Unfinished"], 0, "hard"),

  // general (world culture, computing, crypto/solana)
  q("xgen-01", "general", "How many bits are in a byte?", ["8", "16", "4", "32"], 0, "easy"),
  q("xgen-02", "general", "HTTP status code 404 means:", ["Not Found", "OK", "Forbidden", "Server error"], 0, "easy"),
  q("xgen-03", "general", "In the OSI model, the Internet Protocol (IP) operates primarily at which layer?", ["Network", "Transport", "Application", "Physical"], 0, "hard"),
  q("xgen-04", "general", "Which language is primarily used for styling web pages?", ["CSS", "HTML", "SQL", "JSON"], 0, "easy"),
  q("xgen-05", "general", "In computing, RAM is typically:", ["Volatile memory", "Permanent disk storage", "A network protocol", "A display standard"], 0, "easy"),
  q("xgen-06", "general", "SHA-256 is a:", ["Cryptographic hash function", "Symmetric cipher", "Public-key algorithm", "Compression codec"], 0, "medium"),
  q("xgen-07", "general", "A blockchain is best described as a:", ["Append-only ledger of blocks", "Central SQL database", "Peer-to-peer file folder only", "Single encrypted email"], 0, "easy"),
  q("xgen-08", "general", "A seed phrase should be:", ["Kept secret and never shared", "Posted for account recovery", "Sent to support when asked", "Stored in a public Discord"], 0, "easy"),
  q("xgen-09", "general", "A private key should be:", ["Never shared with anyone", "Emailed to the exchange", "Shown to prove you are human", "The same as your username"], 0, "easy"),
  q("xgen-10", "general", "In public-key cryptography, a digital signature is created with the:", ["Private key", "Public key only", "IP address", "Block height"], 0, "medium"),
  q("xgen-11", "general", "Proof of stake typically selects block producers using:", ["Staked tokens / stake weight", "Always raw electricity use only", "CAPTCHA races", "Email verification"], 0, "medium"),
  q("xgen-12", "general", "A cryptocurrency wallet mainly stores:", ["Keys that control on-chain funds", "Physical coins", "The entire internet", "Bank routing numbers only"], 0, "easy"),
  q("xgen-13", "general", "An NFT typically represents:", ["A unique on-chain token", "A share of a company by default", "Unlimited identical coins", "A password manager"], 0, "easy"),
  q("xgen-14", "general", "Solana programs are commonly written in:", ["Rust", "PHP", "Excel formulas", "COBOL"], 0, "medium"),
  q("xgen-15", "general", "SPL on Solana most often refers to:", ["Solana Program Library tokens", "A stock ticker", "A web browser", "A Linux distro"], 0, "medium"),
  q("xgen-16", "general", "On Solana, a transaction is typically signed by:", ["The fee payer / required signers' private keys", "The RPC provider's password", "The block explorer", "A random validator with no keys"], 0, "medium"),
  q("xgen-17", "general", "An RPC node is mainly used to:", ["Submit and query blockchain data", "Print seed phrases", "Mint physical coins", "Host only email"], 0, "medium"),
  q("xgen-18", "general", "A Solana account's data is owned by:", ["A program (program id)", "Whoever last viewed it", "Twitter", "The token's ticker"], 0, "hard"),
  q("xgen-19", "general", "Rent on Solana accounts is related to:", ["Keeping account data stored on-chain", "Electricity bills at home", "App Store fees", "Domain DNS only"], 0, "hard"),
  q("xgen-20", "general", "A validator on a proof-of-stake network generally:", ["Produces/votes on blocks and is bonded by stake", "Prints banknotes", "Runs only a website CDN", "Issues passports"], 0, "medium"),
  q("xgen-21", "general", "Phishing in crypto usually tries to steal:", ["Seed phrases or keys", "Your favorite color", "Block hashes only", "Public explorer URLs"], 0, "easy"),
  q("xgen-22", "general", "A smart contract on Solana is typically a:", ["On-chain program", "PDF legal contract", "Twitter poll", "Hardware wallet brand"], 0, "medium"),
  q("xgen-23", "general", "Transaction fees on many chains exist mainly to:", ["Pay for inclusion and deter spam", "Fund a single CEO salary only", "Buy GPUs for users", "Replace hashing"], 0, "medium"),
  q("xgen-24", "general", "Decentralization in a blockchain usually means:", ["No single party fully controls the ledger", "One company owns all keys", "One data center is enough", "A king appoints validators"], 0, "easy"),
  q("xgen-25", "general", "A public key can typically be shared:", ["Yes — it does not spend funds by itself", "Never, it is the seed phrase", "Only with the IRS by law in every country", "Instead of a private key to sign"], 0, "medium"),
  q("xgen-26", "general", "A 12- or 24-word seed phrase is used to:", ["Derive wallet keys", "Set the gas price", "Name a validator", "Choose a block explorer theme"], 0, "easy"),
  q("xgen-27", "general", "If someone asks you to \"authenticate\" by typing your seed phrase into a website, you should:", ["Refuse — it is almost certainly a scam", "Do it if the site looks official", "Share only 11 words", "Send a photo of the paper backup"], 0, "easy"),
  q("xgen-28", "general", "Which ISO country code is used for Japan?", ["JP", "JA", "JN", "JPN as 2-letter"], 0, "medium"),
  q("xgen-29", "general", "The UN headquarters is in which city?", ["New York", "Geneva only as HQ", "Brussels", "Vienna only as HQ"], 0, "easy"),
  q("xgen-30", "general", "The Nobel Peace Prize is awarded in which city?", ["Oslo", "Stockholm", "London", "Paris"], 0, "medium"),
  q("xgen-31", "general", "The World Wide Web was invented by:", ["Tim Berners-Lee", "Bill Gates", "Steve Jobs", "Linus Torvalds"], 0, "medium"),
  q("xgen-32", "general", "Unicode is primarily a:", ["Character encoding standard", "Video codec", "Routing protocol", "File system"], 0, "medium"),
  q("xgen-33", "general", "In chess, the piece that moves in an L-shape is the:", ["Knight", "Bishop", "Rook", "Queen"], 0, "easy"),
  q("xgen-34", "general", "A leap year has how many days?", ["366", "365", "364", "360"], 0, "easy"),
  q("xgen-35", "general", "The International Space Station orbits:", ["Earth", "the Moon only", "Mars", "the Sun as a planet"], 0, "easy"),
  q("xgen-36", "general", "What does \"SSL/TLS\" mainly protect?", ["Data in transit (encryption)", "CPU clock speed", "Disk fragmentation", "Font rendering"], 0, "medium"),
  q("xgen-37", "general", "A Merkle tree is used in blockchains mainly to:", ["Commit to many transactions efficiently", "Draw UI buttons", "Store seed phrases", "Replace signatures"], 0, "hard"),
  q("xgen-38", "general", "Ed25519 is a:", ["Digital signature scheme", "Hash of Bitcoin blocks only", "Solana ticker", "Wallet brand"], 0, "hard"),
  q("xgen-39", "general", "On Solana, a \"slot\" is closest to:", ["A unit of time in the leader schedule", "A type of NFT royalty", "A Discord role", "A seed word"], 0, "hard"),
  q("xgen-40", "general", "A hardware wallet's main security benefit is:", ["Keys stay in a dedicated device", "It hides your public address forever", "It removes all fees", "It makes RPC unnecessary"], 0, "medium"),
  q("xgeo-27", "geography", "The Durand Line is the border between Afghanistan and:", ["Pakistan", "Iran", "India", "Tajikistan"], 0, "hard"),
  q("xgeo-28", "geography", "Which is the world's largest inland body of water by surface area?", ["Caspian Sea", "Lake Superior", "Lake Victoria", "Black Sea"], 0, "hard"),
  q("xhis-27", "history", "The Peace of Westphalia (1648) ended which conflict?", ["Thirty Years' War", "Hundred Years' War", "War of the Spanish Succession", "Seven Years' War"], 0, "hard"),
  q("xhis-28", "history", "The Battle of Midway (1942) was fought primarily in which ocean?", ["Pacific Ocean", "Atlantic Ocean", "Indian Ocean", "Arctic Ocean"], 0, "hard"),
  q("xsci-27", "science", "Which Kepler law says a planet sweeps equal areas in equal times?", ["Second", "First", "Third", "Zeroth"], 0, "hard"),
  q("xsci-28", "science", "The half-life of a radioactive isotope is the time for:", ["Half the nuclei to decay", "All nuclei to decay", "Temperature to halve", "Mass to vanish"], 0, "hard"),
  q("xmat-21", "math", "The Euler characteristic of a sphere (V − E + F) is:", ["2", "0", "1", "4"], 0, "hard"),
  q("xmat-22", "math", "Bayes' theorem relates P(A|B) to P(B|A) using:", ["P(A) and P(B)", "only P(A)", "only the mean", "the derivative of A"], 0, "hard"),
  q("xent-27", "entertainment", "The Ring Cycle (Der Ring des Nibelungen) was composed by:", ["Wagner", "Mozart", "Verdi", "Stravinsky"], 0, "hard"),
  q("xent-28", "entertainment", "The original DOOM (1993) was developed by:", ["id Software", "Valve", "Blizzard", "Epic Games"], 0, "hard"),
  q("xgen-41", "general", "A Solana transaction message's recent blockhash is mainly used to:", ["Expire stale transactions / prevent replay", "Store the seed phrase", "Set the token name", "Choose an NFT image"], 0, "hard"),
  q("xgen-42", "general", "An associated token account (ATA) on Solana is typically derived from:", ["Wallet + mint + token program", "Only the ticker symbol", "The validator vote key", "The RPC URL"], 0, "hard"),
  q("xgen-43", "general", "Proof-of-history on Solana is best described as:", ["A verifiable delay sequence used in scheduling", "A replacement for signatures", "A type of NFT", "A wallet brand"], 0, "hard"),
  q("xgen-44", "general", "AES is primarily a:", ["Symmetric encryption algorithm", "Hash function", "Public-key signature scheme", "Consensus protocol"], 0, "hard"),
];

module.exports = Object.freeze(EXTRA_QUESTIONS);
